/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetojframevilana;


import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author xenin
 */
public class inicial extends javax.swing.JFrame {
    private Object dadosNasc;
    private Date dataNascimento;
    int idade;
 
    
    /**
     * Creates new form inicial
     */
    public inicial() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNOME = new javax.swing.JLabel();
        campo_usuario = new javax.swing.JTextField();
        labelDATA = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        labelCPF = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        labelCURSO = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        labelSÉRIE = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        labelSEXO = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        labelRESPONSAVEL = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNOME.setBackground(new java.awt.Color(0, 0, 0));
        labelNOME.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelNOME.setText("NOME DO ALUNO:");
        jPanel1.add(labelNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        campo_usuario.setBackground(new java.awt.Color(240, 240, 240));
        campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(campo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 370, 30));

        labelDATA.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelDATA.setText("DATA DE NASCIMENTO:");
        jPanel1.add(labelDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 20));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 30));

        labelCPF.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelCPF.setText("CPF:");
        jPanel1.add(labelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, 30));

        labelCURSO.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelCURSO.setText("CURSO:");
        jPanel1.add(labelCURSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        jRadioButton1.setText("T.I");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        jRadioButton3.setText("ELETRO");
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        labelSÉRIE.setFont(new java.awt.Font("Linux Biolinum G", 1, 14)); // NOI18N
        labelSÉRIE.setText("SÉRIE:");
        jPanel1.add(labelSÉRIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "1º ano", "2º ano", "3º ano", "4º ano" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        labelSEXO.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelSEXO.setText("SEXO:");
        jPanel1.add(labelSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Masculino", "Feminino" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 120, -1));

        labelRESPONSAVEL.setFont(new java.awt.Font("Linux Biolinum G", 1, 13)); // NOI18N
        labelRESPONSAVEL.setText("NOME DO RESPONSÁVEL:");
        jPanel1.add(labelRESPONSAVEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 370, 30));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Linux Biolinum G", 1, 14)); // NOI18N
        jButton2.setText("CADASTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Linux Biolinum G", 1, 14)); // NOI18N
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FIGURINHAS/WhatsApp Image 2024-03-20 at 08.09.51.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed

    
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //cadastra
        String nome = campo_usuario.getText();
        String Responsavel = jTextField1.getText();
        
        if (nome.isEmpty()){
            JOptionPane.showMessageDialog(this,  "INFORME O NOME");
            campo_usuario.requestFocus();
            
        } else if (jFormattedTextField1.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(this,  "INFORME A DATA");
            jFormattedTextField1.requestFocus();
            
        } else if (jFormattedTextField2.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(this,  "INFORME O CPF");
            jFormattedTextField2.requestFocus();
            
        } else if (jTextField1.isEnabled() && Responsavel.isEmpty()) {
                JOptionPane.showMessageDialog(this, "INFORME O NOME DO RESPONSAVEL!");
                jTextField1.requestFocus(); 
        
        } else if ( jComboBox2.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(this,  "SELECIONE UMA SERIE!!");
           
        } else if ( jComboBox1.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(this,  "SELECIONE UM GENERO!!");
        
        } else if (!jRadioButton1.isSelected() && !jRadioButton3.isSelected()) {
            JOptionPane.showMessageDialog(this, " SELECIONE UM CURSO");
            
        }else {
            
            String curso = null;
            String serie = jComboBox2.getSelectedItem().toString();
            String genero = jComboBox1.getSelectedItem().toString();
            
            if (jRadioButton1.isSelected()) {
                curso = jRadioButton1.getText();
            } else if (jRadioButton3.isSelected()) {
                curso = jRadioButton3.getText();    
            }
            
            if (Responsavel.isEmpty()) {
                JOptionPane.showMessageDialog(this, "        CADASTRO REALIZADO!\nAQUI ESTÃO SUAS INFORMAÇÕES:\n\n" + "NOME DO ALUNO: " + nome + "\nDATA DE NASCIMENTO: " + jFormattedTextField1.getText() + "\nIDADE :" + idade +  "\nCURSO : " + curso + "\nSERÍE :" + serie  + "\nGENERO: " + genero);    
                 
            } else {
                JOptionPane.showMessageDialog(this, "        CADASTRO REALIZADO!\nAQUI ESTÃO SUAS INFORMAÇÕES:\n\n" + "NOME DO ALUNO: " + nome +  "\nRESPONSAVEL: " + Responsavel + "\nDATA DE NASCIMENTO: " + jFormattedTextField1.getText() + "\nIDADE: " + idade + "\nCURSO : " + curso + "\nSERÍE :" + serie  + "\nGENERO: " + genero);
         
            }
        }
         
    }//GEN-LAST:event_jButton2ActionPerformed
    
    int calcularIdade(Date dataNascimento) {
        Calendar dataNasc = Calendar.getInstance();
        dataNasc.setTime(dataNascimento);
        
        Calendar hoje = Calendar.getInstance();
        hoje.getTime();
        
        idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);
        dataNasc.add(Calendar.YEAR, idade);
        
        if (hoje.before(dataNasc)) {
            idade--;
        }
        
        
        return idade;
        
    }
       
       
                                     
    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
    
        dataNascimento = null;
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);
       
        try {
            dataNascimento = formatoData.parse(jFormattedTextField1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  "Data inválida!");
            jFormattedTextField1.requestFocus();
        }
        
        if (calcularIdade(dataNascimento) < 18) {
            jTextField1.setEnabled(true);
        } else {
             jTextField1.setEnabled(false);
        }
        
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campo_usuarioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCURSO;
    private javax.swing.JLabel labelDATA;
    private javax.swing.JLabel labelNOME;
    private javax.swing.JLabel labelRESPONSAVEL;
    private javax.swing.JLabel labelSEXO;
    private javax.swing.JLabel labelSÉRIE;
    // End of variables declaration//GEN-END:variables
}
